### ISSUE TITLE
Project Deliverables

### ISSUE THREAD

**Issue by joseph-hellerstein** [jfrostad/hpc-housing-quality#4]
Have you looked at the factors cited in the US Census housing quality indicator (https://www.huduser.gov/publications/pdf/AHS_hsg.pdf)? One project scope is to visualize a subset of these data (or, at least quality indicators you have access to) for the geography you are studying.

**Comment by jfrostad** [comment]
Joe, thank you for the suggestion. We decided not to use data from HUD because it is from a developed country context and therefore not generalizable. Furthermore, HUD has much more detailed information on housing quality so the majority of the indicators within are not present in our dataset.
